### ISSUE TITLE
How to get Collection in a list ?

### ISSUE THREAD

**Issue by Sadmansamee** [siegesmund/SwiftDDP#1]
How to get collection returned as Array after subscription ? or how to get subscription returned value?
I tried  with Meteor.collection("collectionName")  after proper subscription
I did not get any value , it gives me nil.

**Comment by siegesmund** [comment]
Hi, @Sadmansamee  - 

1) Create an array. 
2) To get a table in a list, subclass AbstractCollection and override the following methods:
	a) documentWasAdded(collection:id:fields:)
	b) documentWasChanged(collection:id:fields:cleared)
	c) documentWasRemoved(collection:id)
3) In each of the subclassed methods add, update or remove your document.

**Comment by Sadmansamee** [comment]
cool.. thanks... and your new example demonstrate the procedure I think.. looking forward to it,
