### ISSUE TITLE
Keep sending request to server

### ISSUE THREAD

**Issue by DelattreAdixon** [siegesmund/SwiftDDP#101]
Hi, thank you for your library.
I had a problem, I did a simple method call to server.
Even thought I call it once, it keep calling this method.
Any ideas?

`

                        let parameters = [SessionService.getUserId(), card.mongoId]
                        Meteor.call("codeswops.request", params: parameters) { result, error in

                            print("-- result --");
                            print(result);                            
                        }

`

Alain

**Comment by siegesmund** [comment]
That should only execute once. Where is the snipped above located in your code?

**Comment by DelattreAdixon** [comment]
I've added a button, every time the user click on a button the call is done.
This is really weird, the App continue to call this method randomly.
Should I close the connexion?
Did I forget something before or after?
Your example seems simple, I have no idea why it keep calling the method.

`
    @IBAction func share(_ sender: Any) {
        if NetworkService.isConnectedToNetwork(){
            
            
            
            if let button = sender as? UIButton,
               let card = CardService.getBy(userId: SessionService.getUserId())
                {
                if button.superview != nil {
                    
                    Meteor.client.connect(ConstanteService.METEOR_SERVER) { (result) in
                        print("--> CONNEXION B <--")
                        print(result)

                        //Supprime la carte si existe
                        let parameters = [SessionService.getUserId(), card.mongoId]
                        Meteor.call("codeswops.request", params: parameters) { result, error in

                            print("-- result --");
                            print(result);
                                                            
                            }
                        }
                    }
                    
                }
            }
        }
        else{
            let str1 = NSLocalizedString("Network Error", comment: "Meeting page")
            let str2 = NSLocalizedString("Please try again", comment: "Meeting page")
            NotificationService.popupAlert(object: self, title: str1, message: str2)
        }
    }
    
`

**Comment by DelattreAdixon** [comment]
I think I know why it does not work.
I used 

> Meteor.client.connect

instead of

> Meteor.connect

Seems to work now.
