### ISSUE TITLE
Meteor.unsubscribe() not working.

### ISSUE THREAD

**Issue by mahadevTW** [siegesmund/SwiftDDP#14]
my requirement is like i want to unsubscribe and subscribe on the flow.

**Comment by mahadevTW** [comment]
Always try to connect, and through an error "Swift ddp connection closed with error 1000, clean true "
and in loop try to connect -> again fail->again subscription fail....

**Comment by siegesmund** [comment]
Can you share the code you're trying to run to connect and subscribe?

**Comment by mahadevTW** [comment]
I have a code given below. Once error come "Swift ddp connection closed with error 1000, clean true " it tries to reconnect  , So calls Meteor.connect but fail to subscribe and shows "already subscribed" and same cycle repeats. Also I don't get any updates from server. And also I am not getting any 'pong' messages. I am new at swift so it may be my implementation mistake. Thanking you in anticipation. 
although i am having god network connection, it gives me error periodically.
 
`func connectToServer(collectionId: String) -> Bool {
        Meteor.connect(Config.URL) {
            self.subscribe(collectionId)
        }
        return true
    }
    
    
    private func subscribe(collectionId : String) {
        Meteor.subscribe("collection name" , params: [collectionId]) {
            self.collectionId = collectionId
            self.collectionSubscriptionIsReady("connected")
        }
    }
    
    
    private func collectionSubscriptionIsReady(result : String) {
        print("Subscribed to collectoin ");
        delagate?.connected(result)
    }`

**Comment by siegesmund** [comment]
I don't see anything obviously wrong, but you're wrapping all of the Meteor methods in your own class, and I wonder how you're using that class.

1. First, have you enabled logging?  ``` swift Meteor.client.logLevel = .Debug ``` before you connect. That would enable you to see pongs, as well as other debug messages. 
2. Where are you making your connection and subscription? You should only do this once in the app, and doing this in your AppDelegate is a good place to do it.

**Comment by SwapnilBGaikwad** [comment]
I have one app in which I need to subscribe to the one collection with specific ID as like mahadevTW's code. 
If user want to open another data set in same collection with different ID, So we need to subscribe to the another Data Set from the same collection. So I need to unsubscribe and again resubscribe to the same collection with new ID. 
Once reconnection is done it shows "Swift ddp connection closed with error 1000, clean true "  and it will again subscribe and the cycle continues.

Due to different ID I need to call subscribe multiple times , which leads to previous error "connection closed"
My Server side code of publish is as follows : 

`Meteor.publish('mindmap', function (id) {
   return Mindmaps.find({$or:[{_id:id},{rootId:id}]});
});`

And subscribe code is similar to MahadevTW.
So Is their be any appropriate way to resubscribe  to the same collection with different parameters.

**Comment by siegesmund** [comment]
Thanks @SwapnilBGaikwad and @mahadevTW . I haven't encountered this issue before. I think there's an issue here, but it's tough to say what the issue is without being able to run the code. Would it be possible for one or both of you create a github repo with code that reproduces this issue?

**Comment by SwapnilBGaikwad** [comment]
I have created the repo on git hub which will shows the above connection closed error.
Here is the link of git hub repo.

https://github.com/SwapnilBGaikwad/SampleSwiftDDPCode.git

So please tell me proper way to deal with such situation in which I need to 
subscribe to the collection with the same collection name but with different collection id.

**Comment by siegesmund** [comment]
@SwapnilBGaikwad 

I see now what you are doing. 

Please see the [todos example](https://github.com/siegesmund/SwiftDDP/tree/master/Examples/Dictionary/SwiftTodos). It illustrates exactly what you are trying to do. 

The short answer is: handle your subscription when you instantiate your view controller. Unsubscribe to the subscription when it will disappear. viewWillDisappear is a good place to do this, as shown in the example.

Second, and importantly, you should only instantiate Meteor once, and this should probably be done in your app delegate. Again, see the example. You are trying to reconnect each time the user moves to MapTableViewController via your MeteorTracker class that wraps Meteor. This is wrong. So, one connection per app session.

I would get rid of the MeteorTracker class. Unless you instantiate MeteorTracker in AppDelegate, and remove the subscription logic from it, you really can't handle the subscriptions correctly. And if you do that, it's not doing much as a wrapper. 

Finally, I ran your code for about 15 minutes, in several sessions and didn't get the "Swift ddp connection closed with error 1000, clean true ."

**Comment by SwapnilBGaikwad** [comment]
Thank you for your suggest I have implemented in my app and seems to be working fine. 
But now I need to open my app from using custom URL scheme.
So when I opened for first time and subscribed and pressed home then try to open the app with new subscription parameter (id) passed in URL. So it says already subscribed and new subscription fails as expected.
In this condition ,  is their be any way to reset the things that are already subscribed when entered in AppDelegate method :

`func application(app: UIApplication, openURL url: NSURL, options: [String : AnyObject]) -> Bool`

**Comment by siegesmund** [comment]
I'm not sure I understand what you're trying to do. The way to reset a subscription is to unsubscribe from the publication.

**Comment by SwapnilBGaikwad** [comment]
If I opened app and subscribed with specific subscription parameter (id).
Now my app is connected and subscribed state.
In my app I am unsubscribing the collection in viewWillDisappear.
If subscription is done app and user then open app using URL scheme
e.g. myapp://__id__
then it simple say already subscribed as expected.
So I need to know in such a condition how to unsubscribe to collection.

If I unsubscribe when app goes in background then user will not get updates when user open the app present in background.

**Comment by siegesmund** [comment]
In this instance, I think the appropriate action is to unsubscribe and then resubscribe. Unsubscribe from your publications when the app will enter the background, and resubscribe when when the app becomes active again.

**Comment by SwapnilBGaikwad** [comment]
I have implement the app with functionality of opening app through URL. So when user clicks the like app open's the mindmap.
But their are some issues in it. 
My server side Website is www.mindit.xyz. User can subscribe to collection with root Id of mindmap and server will only publish only part of mindmap collection.

Here is the link of my repo:
https://github.com/Allminds/mind-it-ios.git

So please tell what is going wrong in the app.
**Subscription Cycle**
TableViewController 
viewWillAppear -> Subscribe
viewDidDisappear -> unSubscribe

applicationDidEnterBackground -> Subscribe
applicationDidBecomeActive -> Unsubscribe

**Issues**
Collection get unsubscribed while opening app thought URL.
Check the log which will show the above error.

**Comment by SwapnilBGaikwad** [comment]
Your suggestion really helped me to resolve all of the error.
Thanks for your support.
:+1:
