### ISSUE TITLE
Issues with subscriptions after reconnecting when resuming the app

### ISSUE THREAD

**Issue by mjgaylord** [siegesmund/SwiftDDP#18]
This is either a bug or I am not doing something correctly. I am subscribing to 3 collections on startup and everything works really well. But when I background the app and wait until the web socket connection to timeout and close, then resume the app, the connection is reconnected successfully, but my subscriptions are not updating when data on the server changes. I am not receiving any data either in the logs. Is there a specific way to reconnect my subscriptions? Or do I need to unsubscribe / resubscribe again?

**Comment by mjgaylord** [comment]
#19 I think this solves the issue, but I am not sure if it has any knock-on effects in the library further down the road

**Comment by siegesmund** [comment]
This is an issue that should be addressed. Thanks for the pull request - I've commented there.

**Comment by siegesmund** [comment]
Closing this issue...
