### ISSUE TITLE
How to use Meteor.loginWithGoogle.

### ISSUE THREAD

**Issue by SwapnilBGaikwad** [siegesmund/SwiftDDP#21]
I have used the Meteor.loginWithGoogle and it opens webView for login of google and it prompts allow or deny and in log it shows 
'There was no JSON here'
So how to pass JSON and get the login done.

Please tell me the proper way to  use google authentication for IOS 8.0.
I have installed pod "SwiftDDP", "~> 0.2.0"
And it's working fine But it requires minimum version of 9.0.
For platform :ios, '8.0'
is their be any way to do the same.

**Comment by siegesmund** [comment]
You don't have to manually pass any JSON. Have you set up Google login on the server? When you set it up, did you select redirect?

**Comment by SwapnilBGaikwad** [comment]
1) I have create app on console.developer.google.com.
2) Given an app Authorised JavaScript origins
3) Also Authorised redirect URIs.
4) Now my app opens one page for login and prompts for allow or deny. If I pressed allow then also nothing is happening and in my Log file shows **"There was no json here"**.
So please tell me how to deal with this problem.
Thank you.
