### ISSUE TITLE
Swift 2.2 Unknown attribute @asmname

### ISSUE THREAD

**Issue by achirkof** [siegesmund/SwiftDDP#24]
Hello.
Because of new version of Swift now we have an error in module SwiftWebSocket because `@asmname` was changet to `@_silgen_name`. Could you please update repo.
See details [here](https://github.com/tidwall/SwiftWebSocket/issues/28).
Thanks.

**Comment by siegesmund** [comment]
You're using Carthage, I assume?

**Comment by achirkof** [comment]
@siegesmund no, cocoapods. I met this issue yesterday after update Xcode(and also Swift).

**Comment by siegesmund** [comment]
Ok, at the moment, it looks to me like the latest version of SwiftWebSocket on Cocoapods is 0.2.5. 0.2.6 adds support for Swift 2.2.

I've opened an issue with SwiftWebSocket's author. 

If you're seeing something different, let me know.

**Comment by achirkof** [comment]
SwiftWebSocket's repo already updated to new version. I think you should update dependency to last commit.

**Comment by siegesmund** [comment]
Yes, I will update later today.

**Comment by siegesmund** [comment]
I've updated the spec and pushed to Cocoapods.
