### ISSUE TITLE
Handling changing dependencies of subscription

### ISSUE THREAD

**Issue by leandermelms** [siegesmund/SwiftDDP#25]
I'm currently stuck in dealing with changing params of a subscription call. Specifically, I'm passing location updates as param in order to fetch updated results from the server. 

To my knowledge, Meteor re-subscribes whenever a reactive data source changes. For example:

```javascript
Template.Lists_show_page.onCreated(function() {
  this.getListId = () => FlowRouter.getParam('_id');

  this.autorun(() => {
    this.subscribe('Todos.inList', this.getListId());
  });
});
```

> Technically, what happens when one of these reactive sources changes is the following:
> 
> 1. The reactive data source invalidates the autorun computation (marks it so that it re-runs in the next Tracker flush cycle).
> 2. The subscription detects this, and given that anything is possible in next computation run, marks itself for destruction.
>3. **The computation re-runs, with .subscribe() being re-called either with the same or different arguments.**
> 4. If the subscription is run with the same arguments then the “new” subscription discovers the old “marked for destruction” subscription that’s sitting around, with the same data already ready, and simply reuses that.
> 5. If the subscription is run with different arguments, then a new subscription is created, which connects to the publication on the server.
> 6. At the end of the flush cycle (i.e. after the computation is done re-running), the old subscription checks to see if it was re-used, and if not, sends a message to the server to tell the server to shut it down.

Should something similar done here as well? Simply re-subscribing as a short cut does not seem to work, as SwiftDDP then complains that `> You are already subscribed to deals/list`

Any help / hints are greatly appreciated!

**Comment by siegesmund** [comment]
Right now, I believe you'll need to unsubscribe/resubscribe with new arguments to get this behavior. This pattern tends to work much of the time in iOS - subscribe in viewWillAppear() and unsubscribe in deinit().

That said, I am looking at changing this behavior in the next release. To be clear, where is the quoted text from?

**Comment by leandermelms** [comment]
Thank you for the fast reply! I've tried to follow your advice but I'm not sure if I got it right. My approach: 

```swift
    var coords = [String: Double]() {
        didSet (previousCoords) {
            if coords != previousCoords {
                Meteor.unsubscribe("deals/list" ) {
                    Meteor.subscribe("deals/list", params: [self.coords]) {
                        self.appDelegate.listsSubscriptionIsReady()
                    }
                }
            }
        }
    }

```

which does not quite work. Could you elaborate how to re-subscribe correctly?

Also, I wondered if it might be more efficient to use CoreData instead and do the filtering logic on the client side. But this would somehow kill the intended reactivity. 

Sorry for leaving out the source. It can be found [here](http://guide.meteor.com/data-loading.html#changing-arguments).

**Comment by siegesmund** [comment]
Cool. Thanks for the link to the Meteor Guide. It wasn't around when I wrote the first draft of this code.

While that's not quite the way I'd do it, it looks plausible. How does it not quite work? i.e. what behavior are you seeing?

**Comment by siegesmund** [comment]
I think that SwiftDDPs behavior should be changed to be in line with the Meteor guide. I'll try to make the changes and test them out this evening (US eastern time). Barring unforeseen complication, will that work for you?

**Comment by leandermelms** [comment]
Thank you very much for your help! If I could somehow assist, I'd be very happy to do so.

**Comment by siegesmund** [comment]
If you'd like to take a crack at the changes, I'd be more than happy to merge a pull request. Otherwise, you can help test the changes.

**Comment by leandermelms** [comment]
I think I'd go for testing the changes as I'm not considering myself to be qualified enough to implement the changes.

**Comment by siegesmund** [comment]
So after reading the Meteor Guide a little more carefully, I think this is a little more complicated and nuanced than I initially thought. It's going to take a little more of a rewrite than I thought initially, so I will try to finish it this weekend. In the meantime, you can still sub/unsub. It may not be ideal, but it will work.

**Comment by siegesmund** [comment]
So there's a dev branch that now allows subs to be modified with new arguments. As with Meteor, changing the sub with new arguments actually creates a new sub and your collection will be the union of the two subs.

This is going to break the api a little because it will make callbacks more complicated to implement on unsubscribes, but I don't think that will be too big a deal. 

Give it a try.

**Comment by leandermelms** [comment]
**Thank you for your efforts!** I really appreciate the work and time you've already put into this.

I wasn't able to unsubscribe on the event of a changing param yet. Whenever I'm attempting to do this, SwiftDDP outputs:

```
[Debug] [DDP] [0x124e3d160] [260] ddpMessageHandler > Received message: {
    id = "deals/list";
    msg = nosub;
}
```

I'm using still using the approach described above. Could you share the way you're doing it?

**Comment by siegesmund** [comment]
So, to confirm, you're on the dev branch. 

You subscribe like this: 

```var subscriptionId = Meteor.subscribe('foo', ['123456'])```

You unsubscribe like this: 
``` Meteor.unsubscribe(withId: subscriptionId)```
This unsubscribes you ONLY to the records that correspond to the argument 123456

If you do this:
``` Meteor.unsubscribe('foo')```
You are subscribing to any and all records associated with that subscription. If you do that a second time, you get 'nosub'.

**Comment by leandermelms** [comment]
Works as aspected. Thank you very much for your help and the guidance. Let me know if there is any way to support your work - I'd be honored.

**Comment by siegesmund** [comment]
No problem. I'd like to continue to test this some more before adding it to a production release. You can help by working with it and letting me know how it works.
