### ISSUE TITLE
Add loginWithFacebook method

### ISSUE THREAD

**Issue by lnmunhoz** [siegesmund/SwiftDDP#3]
This is a hard feature to accomplish? I'm new in Swift and just started to study your code. But couldn't build here following by the same error of my other issue #2.
 
Anyway, It will be nice if we can make login with facebook such as other accounts services that Meteor provides.

**Comment by Sadmansamee** [comment]
yeah loginwithfacebook will be so helpfull.

**Comment by siegesmund** [comment]
@lnmunhoz Hmm. I'll try to reproduce. In the meantime, can you try Cocoapods? That should work.

**Comment by siegesmund** [comment]
@Sadmansamee loginWithFacebook, Twitter et. al. is the next major task. If you have thoughts about how to implement it, or would like to work on it, pull requests are welcome :)

**Comment by siegesmund** [comment]
@lnmunhoz See that you got it working with Cocoapods. I'll investigate the Carthage issue. Thanks.

**Comment by siegesmund** [comment]
Login with facebook implemented in version 0.2.0.
