### ISSUE TITLE
How to update a value from my collection using 2 unique identifiers?

### ISSUE THREAD

**Issue by Jeffrey-Lin** [siegesmund/SwiftDDP#32]
I want to query the collection with 2 unique identifiers. How do I query the collection using 2 unique identifiers and modify the value of one of the fields? 

Sorry, I might not be understanding how MeteorCollection works.

**Comment by siegesmund** [comment]
The short answer is, you'll need to implement this yourself by subclassing or extending MeteorCollection. 

The longer answer is:  MeteorJS is tied to MongoDB on both the client and server. There's nothing approximating MongoDB in iOS, and for serious applications you'll really want to use Core Data, Realm, SQLite or perhaps Couchbase Mobile as your iOS datastore. In this more advanced scenario, SwiftDDP would handle the communication - method calls, pubs and subs - between your client and your mobile datastore. You can see examples of this in the Todos examples.

MeteorCollection is intended to provide scaffolding to create more powerful collections backed by other datastores by providing a built-in object that responds to server changes. While it has a few convenience methods, it's not a full-fledged client datastore like minimongo. 

What you're trying to do is not hard. Just create a method that does it via extension or subclassing.
