### ISSUE TITLE
0.2.2.1 Version Number causes issue during XCode Archive

### ISSUE THREAD

**Issue by austinkettner** [siegesmund/SwiftDDP#34]
As of the latest 0.2.2.1 which is the first release with 4 numerics, 3 dots, anytime an XCode Archive build is submitted to iTunes Connect it throws an error due to this libs info.plist being outside the accepted range for build numbers whereas 0.2.2 was fine.

**Comment by siegesmund** [comment]
That's not good. I need to push a new version which will return the version number back to the three digit format. I'll do it asap, but don't think I'll be able to get to it today.

**Comment by siegesmund** [comment]
New version pushed: 0.3.0. Please note changes to sub api. This should fix this issue I think.

**Comment by siegesmund** [comment]
Thinking this should be fixed. Please reopen if this is still an issue for some reason.
