### ISSUE TITLE
Timestamp conversion fails on 32-bit architecture

### ISSUE THREAD

**Issue by esaounkine** [siegesmund/SwiftDDP#36]
## Background
According to [Swift documentation](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html), the length of Int is determined by the architecture:
- on 32-bit architecture its max size is 2^32
- on 64-bit architecture its max size is 2^64

## The pain
When a timestamp is received from a Meteor server, it is a large number representing the milliseconds since 1/1/1970.
In order to convert it to `NSDate`, the function `timeIntervalSince1970` has to be used, which expects seconds rather than milliseconds.

Currently, the code responsible for conversion executes the following steps:
- extract the `$date` field value from the dictionary
- casts is to `Int`
- divides by 1000
- passes it to the `timeIntervalSince1970` function

This approach fails when the architecture is 32-bit, as the millisecond number (e.g. `1469621311763`) is too large to fit into an Int32 (max value - `2147483647`).

**Comment by siegesmund** [comment]
Yuck. Good catch. Do you have a suggested fix? What hardware are you running this on?

**Comment by esaounkine** [comment]
As a matter of fact, it reproduces quite steadily on iPhone 5 Simulator. 

But I think it'll be smarted to avoid casting and dividing large (and especially architecture-dependent) numbers altogether. I'll prepare a fix and make a pull request for your review.

**Comment by siegesmund** [comment]
Yea, that makes sense. Nice catch. I don't think I've ever run this on the iPhone 5. Thanks for the pull request.
