### ISSUE TITLE
Crash on empty optional fields in MeteorDocument

### ISSUE THREAD

**Issue by esaounkine** [siegesmund/SwiftDDP#38]
### Steps to reproduce
- Subscribe to a collection document model has optional fields. E.g. 
```
class Invoice: MeteorDocument {
    var amount: NSNumber
    var merchantId: String
    var comment: String?
}
```
- Publish a message from server that doesn't contain value in the optional field

### Current behavior
When message is received and is attempted to be parsed, the app crashes with symptoms similar to the one described [here](http://stackoverflow.com/questions/16607960/nsnull-length-unrecognized-selector-sent-to-json-objects) and [here](http://stackoverflow.com/questions/32735035/nsnull-length-unrecognized-selector-sent-to-instance-0x37fc8e48-ios-swift).

### Expected behavior
An empty optional field should be probably treated just as an empty `Optional`.

### Suggestion on implementation
I've tried checking for nullity before adding value to the document; it seems to fix the issue in my case. But I never managed to run the unit tests. Also in case something is going to be done on that level, it will require documentation update.
Anyways, [here](https://github.com/siegesmund/SwiftDDP/compare/master...esaounkine:master) is the code snippet that I'm talking about.

### Observations
Same behavior doesn't occur if the model object is set up with `NSString` type instead of `String`, which makes it even less consistent and hard to rely on.

Maybe there's any other more elegant solution to this?

**Comment by Sadmansamee** [comment]
I had similar problem with null values... then I had to go with abstractcollection way... it will be great if there is nullity checker.

**Comment by siegesmund** [comment]
I don't know if there's a more elegant way to do it, but this works. I've merged your solution into the master branch.
