### ISSUE TITLE
Difference with meteor-ios

### ISSUE THREAD

**Issue by Dev1an** [siegesmund/SwiftDDP#42]
Hi, what is the difference between this package and meteor-iOS? It seems pretty similar, so maybe you should add a section in readme.md about why this library is better or different.

**Comment by siegesmund** [comment]
Yea, that's not a bad idea. The biggest difference is obviously that SwiftDDP is written in Swift, while Meteor-iOS, though interoperable with Swift, is written in Objective-C. There's also beta support for Meteor OAuth accounts, which is unusual and which, I believe, Meteor-iOS lacks.

There are other differences, but Meteor-iOS is a great project, and I believe the Meteor ecosystem is better for having both.

**Comment by Dev1an** [comment]
This is the mail system at host niumatapona.mailfwd.taloha.net.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<DAMIAAN@DPRO.BE>: host DPRO.BE[67.20.78.203] said: 550-Message rejected
    because (niumatapona.mailfwd.taloha.net) 550 [216.75.44.103]:44983 is
    blacklisted. (in reply to RCPT TO command)

**Comment by Dev1an** [comment]
Dear Peter Siegesmund,

The email sent to info@devian.tk with subject
"Re: [siegesmund/SwiftDDP] Difference with meteor-ios (#42)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to info@devian.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
