### ISSUE TITLE
Core Data example main vs. background context

### ISSUE THREAD

**Issue by rokanost** [siegesmund/SwiftDDP#45]
Hiya,

In the Core Data example, I notice that the MeteorCoreDataCollection class saves on the backgroundContext in a performBlock. Lists, for example would be saved on the backgroundContext when subscribed to. In the example the NSFetchedResultsController references this backgroundContext via the stack's managedObjectContext property in the initialization of the controller. Is the backgroundContext safe to use on the main thread in this approach?

Cheers -

**Comment by siegesmund** [comment]
So, first, the Core Data example is outdated vis-a-vis the latest version of Meteor's todos demo app. Meteor's todos was completely rewritten for version 1.3, breaking its API.

As for your question, if I understand what you're asking, the answer is yes. This is an established pattern for reading and writing to core data without interfering with the main thread (and thus causing the UI to pause or stutter).

**Comment by rokanost** [comment]
Thanks!
