### ISSUE TITLE
Is there a way to use this without MeteorDocument etc?

### ISSUE THREAD

**Issue by thatjuan** [siegesmund/SwiftDDP#47]
Thank you for making this package available. It looks like great work!

I wanted to ask whether it was possible to just subscribe and get notifications when a document changes/additions/deletions happen as opposed to having to create local MeteorDocument classes to represent the remote data and all that.

Does that make sense? Thanks!

**Comment by thatjuan** [comment]
I managed to do what I needed to do by extending the "Client" DDPClient that's inside of the Meteor class. It seems a bit hacky, though, and it'd look better if Meteor itself provided a delegate that you can hook into for "raw" updates.

This is what my extension looks like:

```
extension Meteor {
    
    public class Client: DDPClient {
    
        public override func documentWasAdded(collection:String, id:String, fields:NSDictionary?) {
            
            print( "ADDED: \(collection) \(id) \(fields)" )
            
        }
        
        public override func documentWasChanged(collection: String, id: String, fields: NSDictionary?, cleared: [String]?) {
            
            print( "ADDED: \(collection) \(id) \(fields) \(cleared)" )
            
        }
        
        public override func documentWasRemoved(collection: String, id: String) {
            
            print( "REMOVED: \(collection) \(id)" )
            
        }
    
    }
    
}
```

**Comment by Sadmansamee** [comment]
I did in one of my project without [MeteorDocument,Visit [here](https://github.com/siegesmund/SwiftDDP#example-creating-an-array-based-custom-collection) for the the documentation and you can see the Boilerplate I made [here](https://github.com/Sadmansamee/Meteor-iOS-Boilerplate) for demonstration.

**Comment by siegesmund** [comment]
You have identified the key methods, but you should not extend Client. What you are trying to do is already available via AbstracCollection. Just subclass it and override those methods.

**Comment by thatjuan** [comment]
Awesome. I'll give that a whirl. Thanks!
