### ISSUE TITLE
Add watchOS support

### ISSUE THREAD

**Issue by Dev1an** [siegesmund/SwiftDDP#49]
Making the framework available on the watch would be great.

**Comment by siegesmund** [comment]
I'm not developing for watchOS right now. Do you have some insight into what needs to be done to make this happen?

**Comment by Dev1an** [comment]
I think a first step would be to make [SwiftWebSocket](https://github.com/tidwall/SwiftWebSocket) WatchOS compatible

**Comment by siegesmund** [comment]
Hmmm. So that's an issue specific to the library? Or to watchOS?  [Starscream](url), another major Swift websocket library doesn't support it either...

**Comment by Dev1an** [comment]
I wanted this feature but like Josh said in his [very clear answer](https://github.com/tidwall/SwiftWebSocket/issues/45#issuecomment-224874747) It is not possible for the moment to open websockets on the Apple Watch.

I hope this will be a feature in OS 3 but we will see next week...
