### ISSUE TITLE
Should a subscription have _id be default?

### ISSUE THREAD

**Issue by wkniffin** [siegesmund/SwiftDDP#52]
Hey!
I am subscribing to a publication and trying to get the _id of the doc. I could not see it in there without _id included in the fields of the publication or with _id included in the fields. 

Any thoughts?

**Comment by KMicrosystems** [comment]
Code snipped as follows:
`class Person: MeteorDocument{
    var collection: String = "people"
    var userId: String?
    var name: String?
    var _id: String?
}`
When attempting to access _id, nil is always returned even after configuring the subscription to explicitly return _id on Meteor. All other fields are returned properly. When _id is removed from this document, the compiler doesn't tell say that the document is not key-value coding compliant like it would if 'name' was left out, for example. 

Any thoughts/suggestions would be much appreciated. Thanks

**Comment by Sef1995** [comment]
You have to override the init method. The _id field is being set via the init method of the super class MeteorDocument. As an example check out the following code:

```
import Foundation
import SwiftDDP

class JobDocument : MeteorDocument {
    
    var _id: String?
    var type: String?
    var data: [String: AnyObject]?
    var status: String?
    
    required init(id: String, fields: NSDictionary?) {
        super.init(id: id, fields: fields)
        
        self._id = id
    }
    
    override func update(fields: NSDictionary?, cleared: [String]?) {
        super.update(fields, cleared: cleared)
    }
    
    override func setValue(value: AnyObject?, forKey key: String) {
        if (key == "type") {
            self.type = value as? String
        }
        
        if (key == "data") {
            self.data = value as? [String: AnyObject]
        }
        
        if (key == "status") {
            self.status = value as? String
        }
    }
}
```

**Comment by KMicrosystems** [comment]
That worked flawlessly. Thank you for the quick and thorough reply!
