### ISSUE TITLE
Question about getting data after subscription.

### ISSUE THREAD

**Issue by caoool** [siegesmund/SwiftDDP#53]
Hi,
Thanks for the library first!

I'm having some trouble and concerns using subscriptions,
I wonder if I could get some help here.

1. Can I get a simplest example showing the work flow of subscribe as well as print the data.
2. Does MeteorDocument object needs to have exactly the same fields as the collection on the server.

Thanks again!

**Comment by caoool** [comment]
One more question, seems like '''var description: String?''' is not allowed in the class definition MeteorDocument, is there a work around or fix please?
Thanks again!

**Comment by Sef1995** [comment]
Hi @caoool, check out this code:

import Foundation
import SwiftDDP

```
class JobDocument : MeteorDocument {

    var _id: String?
    var type: String?
    var data: [String: AnyObject]?
    var status: String?

    required init(id: String, fields: NSDictionary?) {
        super.init(id: id, fields: fields)

        self._id = id
    }

    override func update(fields: NSDictionary?, cleared: [String]?) {
        super.update(fields, cleared: cleared)
    }

    override func setValue(value: AnyObject?, forKey key: String) {
        if (key == "type") {
            self.type = value as? String
        }

        if (key == "data") {
            self.data = value as? [String: AnyObject]
        }

        if (key == "status") {
            self.status = value as? String
        }
    }
}
```

If you create a variable named "description1" you can check in the method setValue if key == "description" { self.description1 = value as? String }

**Comment by siegesmund** [comment]
To simply capture and print the data, you will want to subclass AbstractCollection, then override the following methods: 
- documentWasAdded
- documentWasChanged
- documentWasRemoved
See the example [creating an array based custom collection](https://github.com/siegesmund/SwiftDDP#example-creating-an-array-based-custom-collection). It does exactly what you're trying to do. Printing the results should be pretty easy from there.

**Comment by Sef1995** [comment]
Every class had a description attribute by default that's why the compiler will give you an error if you try to make a variable "description". That's the reason I suggested to name it otherwise, something like "description1".

**Comment by caoool** [comment]
Thank you very much! 
I missed the bottom part of you reply lol I am blind!

**Comment by caoool** [comment]
One more question, does variables have to match every single collection attribute?

**Comment by Sef1995** [comment]
No, if you want to leave certain objects from your collection out you can do that!

**Comment by siegesmund** [comment]
@caoool are you asking if you can ignore some document properties in the iOS app?

**Comment by caoool** [comment]
Yes like if I have
```
{
  _id: String,
  summary: String,
  title: String
}
```
Can I subclass MeteorDocument like
```
class JobDocument : MeteorDocument {
    var _id: String?
    var summary: String?
}
```
only?

**Comment by Sef1995** [comment]
@caoool If you want to leave the title our your free to do that.

**Comment by caoool** [comment]
Last time I did that it was throwing errors,
But I will try again with the proper code.

Thanks again guys, really helped my project going!

**Comment by siegesmund** [comment]
No problem. I think @Sef1995 has done all of the heavy lifting here. Thanks @Sef1995

**Comment by caoool** [comment]
Thanks @Sef1995 :+1:

**Comment by Sef1995** [comment]
Happy to help :-)

**Comment by mroftalp** [comment]
@Sef1995 @siegesmund Sorry just to clarify, I must change the "description" in my database structure?? Like in the mongoDB itself?

**Comment by Sef1995** [comment]
@mroftalp No just the variable name in your class that extends MeteorDocument.

**Comment by mroftalp** [comment]
Ok thanks :) @Sef1995
