### ISSUE TITLE
Web socket connection closed

### ISSUE THREAD

**Issue by jeffmaynard** [siegesmund/SwiftDDP#59]
I seem to be experiencing closed connections to my websocket. The error that I receive is "Web socket connection closed with code 0. Clean: false". The error occurs as a callback on Meteor.connect 60 seconds after the connection is established. I am looking into potential errors server side right now, but I figured I'd open this issue to see if you could provide any insight in this issue. I noticed some users have experienced this with ObjectiveDDP however I can't seem to figure out the issue or potential solutions. Thanks in advance.

**Comment by siegesmund** [comment]
This is an error message posted by the underlying websocket library. In my experience, this is usually a server-side issue, and it can be a hassle to pin down. 

Out of curiosity, what does your server stack look like? Are you running it locally, or connecting to a remote server? Behind a proxy?  Do you use multiple instances? Is your proxy correctly configured?

**Comment by jeffmaynard** [comment]
Thank you for the prompt reply. Off the bat I know 100% that I am connecting successfully as I can subscribe and call methods. I will look into those other questions and get back to you shortly.

**Comment by wkniffin** [comment]
The server is hosted on Meteor Galaxy and I haven't touched any of the basic settings. So no proxy, should be a single instance. 
No error logs on the server side and the web client connects without any issue or disconnect messages.

**Comment by siegesmund** [comment]
One thing that I can think of that caused something similar to this in early versions of the library was if you subscribed to a massive collection as soon as you connect. You'd essentially block i/o with the transfer/processing of this data, which prevented the client from exchanging heartbeats with the server; not hearing any replies to the heartbeat, the server closed the connection. This should have been fixed however.

**Comment by siegesmund** [comment]
@wkniffin Yea, I wouldn't expect a server side error. It's closing the connection, but not necessarily  as the result of an error. In any event, that's good to know.

**Comment by jeffmaynard** [comment]
Although you it should have been fixed, I can go ahead and try to separate out the subscriptions to see if that changes anything. Thanks for the thoughts and the feedback. I will get back to you with my results.

**Comment by siegesmund** [comment]
@jeffmaynard when you log your subscriptions, how long do they take to complete?

**Comment by jeffmaynard** [comment]
For one use case, I have about 20 subscriptions. These take about 1-3 seconds to complete (total time). It isn't until the ~60sec mark hits that I experience the connection close. 

When you reference the early version of the library having issues with "massive collection" subscription what sort of scale are you talking about?

**Comment by jeffmaynard** [comment]
As another reference point, in another use case I have 2 subscriptions, 1 with 1 document in it and the other with 0 documents. I still experience the connection close ~60 sec.

**Comment by siegesmund** [comment]
What you are describing should not cause this. In the case I was referring to, the client was syncing thousands of documents, and it took 30 sec to a minute to complete.

**Comment by siegesmund** [comment]
Unless your documents are huge, but I doubt this is the case :)

**Comment by jeffmaynard** [comment]
Hahah that is definitely not the case! The documents contain only simple data and nothing fancy. However when I call my first subscription, it returns a set of documents (currently ranging from 0-20 docs in that subscription) and for each of those I loop through subscribe to another subscription. We are going to remove the looping functionality and trim everything down to 2 subscriptions and see the result of that. I will get back to you with my results on that. 

Also, lets say the subscription size eventually contains thousands of documents, but each document is small (containing maybe 5 primitive data types each). Is that something that SwiftDDP would still struggle with today or is that still referring to the older library version?

**Comment by siegesmund** [comment]
It should no longer struggle with it. They're now on different operation queues. Heartbeat has a queue all to itself.

**Comment by jeffmaynard** [comment]
Thanks for that information. So far, after making my changes mentioned above, the only websocket closures have code 1000 and are clean, normal closures. We had to remove a lot of data to test this with so tomorrow when I can, I will test with the previous amount of data we had before to make sure that the code 0, unclean closures don't continue. I will get back to you with my results and will subsequently close this issue.

**Comment by siegesmund** [comment]
For what it's worth, 20 subscriptions is a lot. Firing off up to 20 subscriptions in short succession with each client connect is a heck of a lot. You're stress testing your server with each client connect.

**Comment by jeffmaynard** [comment]
I'm a bit new to the Meteor game so that is good to know. Once @wkniffin heard how I was calling it, we quickly changed things and it seems to be working so far. Like I said, I will test with more docs being returned when I get the chance by tomorrow. 

I will say I have opened a few issues in this library and you are so quick and thorough with your replies. You should be proud for maintaining such a sophisticated package as well as you do. Keep up the good work - I will check back tomorrow.

**Comment by jeffmaynard** [comment]
Everything works great! Thanks again for the assistance.
