### ISSUE TITLE
MeteorCollection

### ISSUE THREAD

**Issue by Sadmansamee** [siegesmund/SwiftDDP#6]
hey @siegesmund 
I'm getting two issue when trying to follow the dictionary way (Simple in-memory persistence) 

below 
1. Cannot assign value of type MeteorCollection<.MeteorDocument.>  to type 'MeteorCollection'
2. Generic parameter 'T' could not be inferred when using on table view functions like "collection.count"

**Comment by Sadmansamee** [comment]
Issue solved
On https://github.com/siegesmund/SwiftDDP/blob/master/Examples/Dictionary/SwiftTodos/Lists.swift

  var collection:MeteorCollection = (UIApplication.sharedApplication().delegate as! AppDelegate).lists

I followed this way then I got that problem there was type mismatch... my mistake when removed ":MeteorCollection" it worked fine...

**Comment by siegesmund** [comment]
Glad you solved it!

**Comment by Sadmansamee** [comment]
thanks...but facing another issue like the collection list  it not initilized even after successful subscription. Like I declare a variable<MeteorCollection> (a class subclassed from MeteorDocument) on appdelegate and use it on other VC and subscribe there just like as you demontrated but then later found out that value is not getting populated , do I need explicitly populate any how?

**Comment by siegesmund** [comment]
You must create a collection that will contain the documents, not a document. Here is an example, from the documentation: 

```swift
class List: MeteorDocument {

    var collection:String = "lists"
    var name:String?
    var userId:String?

}

let lists = MeteorCollection<List>(name: "lists")   // As with Meteorjs, the name is the name of the server-side collection  
Meteor.subscribe("lists") 
```

You might declare the collection in your AppDelegate. It doesn't make any sense to declare a document there.

**Comment by siegesmund** [comment]
By the way, per your original question: you're running into the basics of Swift's strong typing.

You can write it as: 
```swift 
var collection:MeteorCollection = (UIApplication.sharedApplication().delegate as! AppDelegate).lists
 ```

or, more commonly, you can cast it:

``` swift 
var collection = (UIApplication.sharedApplication().delegate as! AppDelegate).lists as! MeteorCollection
```

This is something that you will run into repeatedly in Swift.

**Comment by Sadmansamee** [comment]
actually that was not my question but I'm clear now.

**Comment by siegesmund** [comment]
Great!
