### ISSUE TITLE
Support for OS X

### ISSUE THREAD

**Issue by shauncampbell** [siegesmund/SwiftDDP#60]
It would be useful if SwiftDDP would be able to compile a framework for OS X as well as iOS. I forked and was going to raise a Pull request for this but then I came across this: https://github.com/siegesmund/SwiftDDP/pull/4 .

Looks like it was implemented then reverted? At some point between then and the current master, Is there a complication in supporting OS X or would it be possible to add it back in?

**Comment by siegesmund** [comment]
Yea, so what happened here was this: That pull request, if I remember correctly, just changed the Podfile and revised the supported platforms. At that point, there was noting iOS specific in the code. Then, several versions later, OAuth login support was added, and this specifically used the Cocoa Touch API. 

Right now, the Podfile, and the OAuth login API are the only thing specifically preventing use on OSX.

One option I'd be open to would be to split the OAuth API into a second package. Have you looked at the code in depth? What were your thoughts on it?

**Comment by shauncampbell** [comment]
Ah okay :) That makes sense. From a quick look it looks like the only iOS specific bit is the ViewController for the OAuth display. 

I'm relatively new to building cross-platform frameworks in Swift, but my understanding is that you can include/exclude classes on a per platform basis as well using preprocessor statements to include sections of code based on the os:

http://nshipster.com/swift-system-version-checking/

So my guess is (and I'll try this out and see what happens) if we excluded the OAuth stuff from the build for the OSX target and used the preprocessor statements to exclude the OAuth methods from the API - then that would give us the framework minus the OAuth stuff on OS X.

**Comment by siegesmund** [comment]
Sounds good to me.

**Comment by spunkedy** [comment]
My last PR #69 created the scheme. Which excluded the oauth in the code until it can be added back in. 

I haven't tested it, though you should be able to tweak it

**Comment by siegesmund** [comment]
Awesome. I'll have to give it a go. If you get around to testing it, that would be a big help also, as i'm tied up with other work at the moment.

**Comment by spunkedy** [comment]
I was commenting more for the issue owner. So they can be equipped to do
it.

I'm tied up for the next couple weeks also

**Comment by siegesmund** [comment]
Ah, ok. Thanks.
