### ISSUE TITLE
Core Data and SwiftDDP - Custom sort issue

### ISSUE THREAD

**Issue by RonGafni** [siegesmund/SwiftDDP#61]
Hey, 

I'm using "MeteorCoreData" - https://github.com/siegesmund/MeteorCoreData

When I'm trying to fetch my collection with my custom sort: 

`"let dateDescriptor = NSSortDescriptor(key: "preview_message.submitted_at.$date", ascending: false)"`

Its doesn't work. when conversation is update in the web I get update: 

`fields =     {
        "created_at" =         {
            "$date" = 1469556204651;
        };
    };`

And when I'm reloading the tableview in "controllerWillChangeContent"  I think MeteorCoreData is fetching by "created_at" sort and won't order as I want.

How can I change it? Thank you very much!

**Comment by siegesmund** [comment]
I wouldn't recommend using MeteorCoreData. It's and undocumented, out of date, unfinished project.

**Comment by RonGafni** [comment]
But you can not give me help on this particular issue?
