### ISSUE TITLE
Can't login with facebook 

### ISSUE THREAD

**Issue by DevJS** [siegesmund/SwiftDDP#65]
Hi there,

I'm trying to use SwiftDDP with my Meteor installation but I am encountering some issues with the social authentication.

Here is what I did so far:

1. Install `accounts-facebook` & `social configuration` to setup facebook login on my website. I also used accounts-ui (you should specify in your README that it is required to easily setup social logins) to setup my social login. I configured my facebook login using "redirect" auth. 

2. Try to login on my website using facebook. Works perfectly.

3. I created a new tab bar application using Xcode and added SwiftDDP to my project using cocoapods. I added some code on my AppDelegate and then created an IBAction that launch the login process:

**AppDelegate.swift**

```
Meteor.client.logLevel = .Verbosee
Meteor.connect("ws://localhost:3000/websocket") { }
```

**FirstViewController.swift**

```Meteor.loginWithFacebook("FACEBOOK_APP_ID", viewController: self)```

But I get some problems with the `MeteorOAuthController`.

A. If I delete the app from the simulator and clean the project, then run the project again, it loads correctly the facebook login page. But when I click the blue login button on the facebook page, nothing happens. It just loads indefinitely, but stays on the facebook page.

B. If I close the `MeteorOAuthController` and then open it again, the facebook page is not loaded, I just get a simple blank page with nothing on it.

Any idea about what is causing this problem ?

Thank you,
DevJS

**Comment by siegesmund** [comment]
I can't tell what you're doing without seeing more code. What is inside your IBAction?

**Comment by DevJS** [comment]
Oops sorry I was not very clear on my previous post. The code in the firstViewController is the code inside the IBAction :)

**Comment by DevJS** [comment]
Do you need any more code than that?

**Comment by siegesmund** [comment]
There are a lot of moving parts to this. Could you provide a working example that I can build and run?

**Comment by siegesmund** [comment]
Without any confidential data, obviously.

**Comment by DevJS** [comment]
Here's the Swift project build with Xcode 7 : https://www.dropbox.com/s/d9im1a1j4hd6emw/RocketTester.zip?dl=0

Do you also need the Meteor project? I am running Meteor 1.2.1 and installed accounts-facebook, accounts-ui and service configuration.

**Comment by DevJS** [comment]
I tried to create a new project using Meteor 1.4.1, same problem. Here's the project : https://www.dropbox.com/s/rwql8wsl8uhat57/simple-todos.zip?dl=0

**Comment by sayed19** [comment]
I am facing the same issue. When I try to login, it goes into a infinite loading phase. I have tried with facebook sdk and with out sdk but both approaches leads to the same infinte loading issue. The callback returns no error but our server is getting no request. The log shows below message after hitting the login button. 
**2016-08-09 16:08:35.971 urbanchefs[11111:000000] -canOpenURL: failed for URL: "fbauth2:/" - error: "(null)**  
I am using ddp 0.3.2, ios 8 and Xcode 7.3.1
[fbLoginIssue.zip](https://github.com/siegesmund/SwiftDDP/files/408700/fbLoginIssue.zip)

**Comment by siegesmund** [comment]
@DevJS I see one huge problem with your code that will prevent it from ever working. 

You're passing Meteor.loginWithFacebook a string: "FACEBOOK_APP_ID", instead of the actual App Id that you received from Facebook.

**Comment by siegesmund** [comment]
@sayed19 First, using the Facebook iOS SDK is a completely different login flow. You can do that, but then you won't use SwiftDDP's oAuth login. 

Second, I can't do anything with what you've given me. It's just a code fragment.

**Comment by DevJS** [comment]
Yes I know, for some reasons I just couldn't leave the actual app Id on the code before sending it to you! :) Any idea why this is happening?

**Comment by siegesmund** [comment]
@DevJS Ok, good to know. No, I get a launchServicesError when I try to build and run with XCode 7.3.1

Which version of Swift & XCode are you using?

**Comment by siegesmund** [comment]
@DevJS More to the point, as long as you're passing the correct App Id, I don't see anything wrong with your code. Need it to compile to find out more.

**Comment by DevJS** [comment]
I am using Xcode 7.3.1 & Swift 2.2.x (2.2.1 I think). I don't get this error when I download the project from Dropbox. Have you tried to clean & build the project? Resetting your simulator might solve the problem as well. 

I am trying to figure out what is happening as well.

I added a log in the MeteorOAuthViewController, in the `didFinishLoadingRequest` method of the WKWebView. Apparently, the first time I try to connect with facebook - right after installing the app on the simulator - the method is called and I see my log appearing in the console.

BUT. When I close the app and open it again, and try to connect with facebook, the request starts loading but is never finished. Like the webview has some problems with the request. 

Not sure it helps but this is what I have been doing this morning.

Thank you,
DevJS

**Comment by DevJS** [comment]
Is there any kind of ACL / Security rules I have to apply in my Meteor application to allow my app to connect with facebook ?

**Comment by zahedul** [comment]
Hello @siegesmund ,
code is like:

```
class LoginViewController: UIViewController , NVActivityIndicatorViewable {
    let textFieldEmail : UCTextField = UCTextField()
    let textFieldPassword : UCTextField = UCTextField()
    let loginButton : UCPrimaryButton = UCPrimaryButton()
    let fbLoginButton : UIButton = UIButton()
    let signupLink : UILabel = UILabel()

    override func viewDidLoad() {
        super.viewDidLoad()
        prepareView()
        .......
    }

    private func prepareView() {
        self.view.backgroundColor = UIColor(red:1.00, green:1.00, blue:1.00, alpha:1.00)
        ........
        prepareButtons()
        .......  
    }
    private func prepareButtons() {
        ............
        fbLoginButton.addTarget(self, action: #selector(self.loginWithFacebookWasClicked(_:)) , forControlEvents: .TouchUpInside)
        self.view.addSubview(fbLoginButton)
    }

    func loginWithFacebookWasClicked(sender: AnyObject) {
        print(sender)
        Meteor.loginWithFacebook(AppSettings.FacebookAppID, viewController: self)
    }
..........
}
```

@sayed19  an me working on same project. After giving facebook login information page is stuck. we build button from not . do not use drag-drop in storyboard. 
Do we make anything wrong ? 
<img width="1280" alt="screen shot 2016-08-10 at 3 09 39 pm" src="https://cloud.githubusercontent.com/assets/1929044/17548600/678a753e-5f0e-11e6-9a11-15eb3c28c0ff.png">

**Comment by siegesmund** [comment]
@DevJS Thanks for the version info. No, there are no Meteor-specific access rules to configure. Have you tried the other login methods - Google, Twitter etc. ?

**Comment by siegesmund** [comment]
@DevJS I've had a closer look. Facebook login indeed seems broken.

OAuth login was always a bit hacky because of the need to piggyback on Meteor's complicated OAuth login flow. It uses a very unofficial "api". I don't yet know whether this is due to a change to Meteor's accounts packages in the latest versions, or whether Facebook has made a subtle change to the process that has somehow broken it.

I will look into this more deeply if I can find time, but I can't promise anything. 

Also, I *think* ObjectiveDDP had a working Facebook login implementation that used the Facebook iOS SDK. However, I don't think it allowed you the full Meteor functionality of creating a user if the user hadn't logged in before. You should have a look.

**Comment by DevJS** [comment]
I understand. I hope you will find some time to investigate though, SwiftDDP is more than useful for a lot of people out there.

Thank you for taking the time @siegesmund, 
DevJS

**Comment by aramix** [comment]
Having the same issue. Would appreciate it be fixed. SwiftDDP is the only way for me to write an iOS meteor client as being a web developer)

**Comment by siegesmund** [comment]
@DevJS 
Using Meteor Accounts with mobile is surprisingly complicated, with Facebook being a particular hassle. That's why there has really never been a good mobile solution to the accounts problem. Specifically, Facebook's iOS SDK produces a token that's incompatible with the one that Meteor Accounts is designed to consume via the web api (or, it did last time I looked, a year ago). There was a pull-request to ObjectiveDDP that also involved installing a custom facebook-accounts package via atmosphere. I don't know what became of it.

Meteor hasn't devoted any real resources to the accounts packages in a long time, and because they're closely tied to MongoDB, they're likely to be deprecated if/when Apollo gains traction. They've signaled that they're looking to the community to provide accounts functionality in the future Apollo-centered ecosystem.

I'll try to take a closer look at it, but I would also suggest that a solution that's brittle is probably not something you want to use for a production app. That's why I've always left it tagged as beta. 

@aramix When did Facebook login break for you? As an aside, if you're a web developer, surely you know that Meteor has a Cordova implementation? And React Native also works with Meteor. Both would allow you to code in Javascript. If you haven't looked at React Native, I'd suggest giving it a good look. It's really compelling.

**Comment by aramix** [comment]
@siegesmund
I installed SwiftDDP 2 days ago and just today got the Facebook login part. All I get after logging to Facebook is an infinitely loading blank screen.
Yeah I've used Cordova implementation in several apps but for this one i decided to build a native app. I have used react native before but never with meteor. I'm thinking of moving to react native however considering this part is not stable and can break later too. Thanks for a thorough explanation and great library. :)

**Comment by siegesmund** [comment]
@aramix Yea, React Native is awesome. There is a guide to getting Facebook auth working [here](https://medium.com/@spencer_carli/react-native-meteor-oauth-with-facebook-3d1346d7cdb7#.2ihbqk6oa). I'm going to look closely at this approach this weekend. If it works in React Native and is reasonably, it should also work in Swift.

**Comment by aramix** [comment]
@siegesmund
Thanks a lot :)

**Comment by siegesmund** [comment]
@aramix, @DevJS 
So, I just finished reading the tutorial [here](https://medium.com/@spencer_carli/react-native-meteor-oauth-with-facebook-3d1346d7cdb7#.wb8jsnbut). Most of the work is creating the custom Facebook login handler on the Meteor server side. Then you just call a method from the client with a token from the Facebook iOS SDK. The server-side code is all there. Pretty simple.

**Comment by siegesmund** [comment]
Closing this issue, as OAuth support has been removed from SwiftDDP.
