### ISSUE TITLE
there is no tvOS scheme

### ISSUE THREAD

**Issue by spunkedy** [siegesmund/SwiftDDP#67]
I am not as skilled as I wish I was with swift and xcode. However to get it working I had to rip out anything that had to do with a view controller to get it running. 

I was able to use it with my tvOS app to get subscriptions and make ddp calls though.  I would create a PR but I do not know the proper way to exclude files / functionality from a scheme.

**Comment by siegesmund** [comment]
There's only one thing that depends on a view controller, and that supported the zero-config OAuth. I'm in the process of removing and replacing it with instructions on how to accomplish the same thing with the Facebook iOS SDK. So, the thing that's been holding you up is on its way out, obviating the need to exclude the files.

So, I'm happy to look at a PR for tvOS. tvOS support would be great and integrating it should be easy.

**Comment by spunkedy** [comment]
Once that part is out I will go through and try to get a PR going via adding the scheme. Right now I have the locally modified code working through Carthage.

**Comment by siegesmund** [comment]
I believe all of the iOS specific stuff should be out of the master branch now.

**Comment by spunkedy** [comment]
I will try to check today

**Comment by spunkedy** [comment]
I tried adding in the scheme.

```
=== CLEAN TARGET Nimble-tvOS OF PROJECT Nimble WITH CONFIGURATION Release ===

Check dependencies
target 'Nimble-tvOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform

=== BUILD TARGET Nimble-tvOS OF PROJECT Nimble WITH CONFIGURATION Release ===

Check dependencies
target 'Nimble-tvOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform
```

With the default Cartfile I see that. 

I don't know how intrinsic Nimble is to the usage. However I was able to get it my local version working with just:
- CryptoSwift
- SwiftWebSocket
- XCGLogger

**Comment by siegesmund** [comment]
Nimble is for the DDP tests. I'd imagine that this may just be a matter of updating the Nimble version to the latest version.

**Comment by spunkedy** [comment]
https://github.com/Quick/Nimble/issues/213

**Comment by spunkedy** [comment]
My latest version of carthage with homebrew is 0.16.2 trying to update

**Comment by spunkedy** [comment]
I have it forked, however I cannot get Carthage to build it as a reference. Xcode builds it fine. Would you like me to push the PR over, or wait until I get carthage working. It might be a while because I am about to go on vacation.

**Comment by siegesmund** [comment]
Are you getting the same errors as before?

**Comment by spunkedy** [comment]
No, I just suck right now at adjusting schemes for tvOS. If I change the whole project to use the tvOS sdk it works fine. 

Learning how to make the targets appropriately for carthage to use instead of a differently named scheme is where I am at. 

I will try to look at it this week a little more.

**Comment by siegesmund** [comment]
I've never made a tvOS app, and I don't use Carthage much either, though for other reasons, so I'm not sure I'm much help here.

**Comment by spunkedy** [comment]
haha no worries. I will go through and look at how SwiftWebSocket does it and just mimic it for this code base. It might be a few days though just a heads up

**Comment by siegesmund** [comment]
Sounds like a good approach. Thanks for doing this!

**Comment by spunkedy** [comment]
np.

**Comment by siegesmund** [comment]
Closing this issue as I've merged the pull requests.

**Comment by spunkedy** [comment]
Sounds good.  When you add in the oAuth screens back in, might have to disable them from the schema/ allow for a separation

**Comment by siegesmund** [comment]
If OAuth gets back into the library, it shouldn't conflict in any way with tvOS. To the best of my knowledge, the only iOS specific portion of it was the UIViewController and the WKWebView. Neither of those will be used in a future OAuth implementation.
