### ISSUE TITLE
Date in document looks different in Swift

### ISSUE THREAD

**Issue by mroftalp** [siegesmund/SwiftDDP#70]
```
updatedAt =         { 
            "$date" = 1472005498821; 
        }; 
```
Why does the date looks like this whenever I get the document with data type date?

**Comment by mroftalp** [comment]
Can you provide an example of how to use convertToNSDate? Cause it returns nil to me

**Comment by siegesmund** [comment]
It looks like that because that is the way that dates are represented in DDP. For a better understanding of convertToNSDate, see the [function](https://github.com/siegesmund/SwiftDDP/blob/a8b04db79d2d9c4b06b5a3f1cc25f04268cfee50/SwiftDDP/EJSON.swift#L47) itself.
