### ISSUE TITLE
Support swift 3

### ISSUE THREAD

**Issue by InnaLMC** [siegesmund/SwiftDDP#74]
Will you support swift 3? It would be very helpful

**Comment by siegesmund** [comment]
I intend to, but I'm busy with other work at the moment, so I can't give a timetable. It should take little, however, to port the code to Swift 3. Pull requests are welcome.

**Comment by spunkedy** [comment]
I was not able to easily convert the source to swift 3. It is needed for my projects as well. It will be a little bit before I will have time to learn how to convert it.

**Comment by siegesmund** [comment]
I'll try to carve out some time to work on this. Can you give me a heads up on what the hurdles are going to be?

**Comment by spunkedy** [comment]
26 issues after an auto convert. You have to convert each target schema as well to be updated. I can do that for tvOS after you get it going. 

https://github.com/spunkedy/SwiftDDP

It's checked in not working to my master. I have specific versions tagged in my cartfile for the dependencies. So if you want a "psuedo" starting point grab my cartfile. 

~~The logger dep is in a feature branch quite active. I think it should be soon.~~
It appears to be already pushed 4 hours ago.

https://github.com/DaveWoodCom/XCGLogger/commit/636e042ce15a241ddeffc62f80839fadcc1bfa90


![screen shot 2016-09-20 at 12 41 55 pm](https://cloud.githubusercontent.com/assets/690735/18682010/2776ebde-7f30-11e6-815e-64fcf9c16f41.png)

**Comment by JoshuaUnrau** [comment]
Could we have a timeline as to when this will be done? This library is quite important for me and I am having no luck fixing it myself.

**Comment by JoshuaUnrau** [comment]
I have fixed the library so that it works fine with my app and have been using it for a few weeks. If any one wants access to it please send me a message.

**Comment by Sef1995** [comment]
@JoshuaUnrau could you send a pull request?

**Comment by siegesmund** [comment]
@Sef1995 @JoshuaUnrau Indeed, if you send a pull request, I'll merge it into a Swift 3 branch.

**Comment by spunkedy** [comment]
I can test it if you do.

**Comment by JoshuaUnrau** [comment]
Sorry I am relatively inexperienced with GitHub. Which branch should I
request to pull from? Anyway I attached my files to this email.

**Comment by spunkedy** [comment]
Here are a couple resources:
https://help.github.com/articles/creating-a-pull-request/
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

I don't see the source attached because it is showing up on the comments section

**Comment by mjgaylord** [comment]
I just submitted a pull request for the Swift 3 upgrade if anyone is interested

The pull request can be found here: #82

**Comment by siegesmund** [comment]
Reviewed and merged.
