### ISSUE TITLE
How can I detect meteor different collection changes ?

### ISSUE THREAD

**Issue by zahedul** [siegesmund/SwiftDDP#75]
Hello, `METEOR_COLLECTION_SET_DID_CHANGE` ... common data change observer. But I need different subscription observer. How can I make it.

thanks in advance

**Comment by siegesmund** [comment]
Just post your own notification from the collection change callbacks.

**Comment by ahmedtahaaroua** [comment]
I have the same problem , I didn't find the collection change callbacks 
Can you please give us an example

**Comment by siegesmund** [comment]
Please read the docs before opening issues. This is covered there. There are three callbacks that run in response to change events: documentWasAdded, documentWasChanged, documentWasRemoved. Post your notification from one of those.
