### ISSUE TITLE
Cannot connect with http or https

### ISSUE THREAD

**Issue by black-lotus** [siegesmund/SwiftDDP#78]
as subject

```
Meteor.connect("http://my.connection.com:3000/websocket") {
            print("//////////////// CONNECT SUCCESS ////////////////////")
}
```

Thank you in advance

**Comment by siegesmund** [comment]
Your connection string is wrong. Websocket connection strings look like this: ```wss://my.connection.com:3000/websocket```

**Comment by black-lotus** [comment]
Hi @siegesmund thank you very much for your response.
so currently we cannot using http or https right ?

**Comment by siegesmund** [comment]
Meteor always uses websockets internally to transmit data between the client and server, not http. Your end application will be served to users over http/https. Make sense?
